# Generated by Django 5.1.6 on 2025-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UserActivity',
                'verbose_name_plural': 'UserActivities',
                'indexes': [models.Index(fields=['user_id'], name='api_useract_user_id_286e34_idx'), models.Index(fields=['timestamp'], name='api_useract_timesta_199b62_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('number_phone', models.CharField(max_length=100)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UserControl',
                'verbose_name_plural': 'UserControls',
                'indexes': [models.Index(fields=['tg_id'], name='api_usercon_tg_id_5f4617_idx'), models.Index(fields=['created_at'], name='api_usercon_created_1d4f61_idx')],
            },
        ),
    ]
